// <auto-generated />
using ASE_Trader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASE_Trader.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200324114036_dummydata")]
    partial class dummydata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview1.19506.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASE_Trader.Models.EntityModels.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PwHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            AccountType = 0,
                            Email = "vk@hotmail.com",
                            FirstName = "Victor",
                            LastName = "Kildahl"
                        },
                        new
                        {
                            UserId = 2L,
                            AccountType = 0,
                            Email = "lm@hotmail.com",
                            FirstName = "Lasse",
                            LastName = "Mosel"
                        },
                        new
                        {
                            UserId = 3L,
                            AccountType = 0,
                            Email = "dt@hotmail.com",
                            FirstName = "David",
                            LastName = "Tegam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
